# Generated by Django 3.0.5 on 2020-08-24 08:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('agent_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('agent_adress', models.CharField(max_length=200)),
                ('agent_contact_phone', models.CharField(max_length=100)),
            ],
            managers=[
                ('agents', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Estates',
            fields=[
                ('estate_id', models.AutoField(primary_key=True, serialize=False)),
                ('estate_title', models.CharField(max_length=100)),
                ('estate_description', models.CharField(max_length=500)),
                ('estate_location', models.CharField(max_length=200)),
                ('estate_area', models.CharField(max_length=4)),
                ('estate_construction_type', models.CharField(max_length=100)),
                ('estate_status', models.CharField(max_length=20)),
                ('estate_completion_year', models.CharField(max_length=4)),
                ('estate_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reapp1.Agents')),
            ],
            managers=[
                ('estates', django.db.models.manager.Manager()),
            ],
        ),
    ]
