# Generated by Django 3.0.5 on 2020-08-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_adress', models.CharField(max_length=200)),
                ('agent_contact_phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estates',
            fields=[
                ('estate_id', models.AutoField(primary_key=True, serialize=False)),
                ('estate_title', models.CharField(max_length=100)),
                ('estate_description', models.CharField(max_length=500)),
                ('estate_location', models.CharField(max_length=200)),
                ('estate_area', models.CharField(max_length=4)),
                ('estate_construction_type', models.CharField(max_length=100)),
                ('estate_status', models.CharField(max_length=20)),
                ('estate_completion_year', models.CharField(max_length=4)),
            ],
        ),
    ]
